openapi: "3.0.2"
tags:
  - OAuth
security:
  - userAuth: []
parameters:
  - name: code
    in: path
    required: true
    description: authorization_code
    schema:
      type: string
      example: some_code
responses:
  '200':
    description: jwt - access_token, refresh_token value
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/get_kakao_id_and_create_jwt'