class UserTopicEnum:
    CREATE_USER = "create_user"
    IS_EXISTS_USER = "is_exists_user"
    GET_USER = "get_user"
    UPDATE_USER_UUID = "update_user_uuid"
    IS_EXISTS_USER_BY_USER_ID = "is_exists_user_by_user_id"
    SET_USER_UUID_TO_CACHE = "set_user_uuid_to_cache"
    IS_VALID_USER_UUID = "is_valid_user_uuid"
    IS_VALID_USER_UUID_FROM_REDIS = "is_valid_user_uuid_from_redis"
    UPDATE_CURRENT_CONNECTION_TIME = "update_current_connection_time"
