version: "3"

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: captain
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgres-data: