"""create jwts table

Revision ID: 04385755e02e
Revises: 3abd50eeaea9
Create Date: 2021-05-20 15:32:35.163234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04385755e02e'
down_revision = '3abd50eeaea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jwts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('access_token', sa.String(length=270), nullable=False),
    sa.Column('refresh_token', sa.String(length=270), nullable=False),
    sa.Column('access_expired_at', sa.DateTime(), nullable=False),
    sa.Column('refresh_expired_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jwts')
    # ### end Alembic commands ###
