"""create blacklists table

Revision ID: 36d4819af983
Revises: 04385755e02e
Create Date: 2021-05-24 18:17:12.104162

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '36d4819af983'
down_revision = '04385755e02e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklists',
                    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True,
                              nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('access_token', sa.String(length=270), nullable=False),
                    sa.Column('expired_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklists')
    # ### end Alembic commands ###
