"""Create UserModel, JwtModel, BlacklistModel table

Revision ID: 4b9f5440b1a3
Revises: 
Create Date: 2021-06-01 10:56:47.743211

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4b9f5440b1a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True,
                              nullable=False),
                    sa.Column('provider', sa.String(length=10), nullable=False),
                    sa.Column('provider_id', sa.String(length=50), nullable=False),
                    sa.Column('group', sa.String(length=10), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('blacklists',
                    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True,
                              nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('access_token', sa.String(length=270), nullable=False),
                    sa.Column('expired_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('jwts',
                    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True,
                              nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('access_token', sa.String(length=270), nullable=False),
                    sa.Column('refresh_token', sa.String(length=270), nullable=False),
                    sa.Column('access_expired_at', sa.DateTime(), nullable=False),
                    sa.Column('refresh_expired_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jwts')
    op.drop_table('blacklists')
    op.drop_table('users')
    # ### end Alembic commands ###
